// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Battleship.Models;

public partial class Battleground
{
    public int Id { get; set; }

    public int? IdMatch { get; set; }

    public bool? FieldHost { get; set; }

    public int? YCord { get; set; }

    public int? FieldA { get; set; }

    public int? FieldB { get; set; }

    public int? FieldC { get; set; }

    public int? FieldD { get; set; }

    public int? FieldE { get; set; }

    public int? FieldF { get; set; }

    public int? FieldG { get; set; }

    public int? FieldH { get; set; }

    public int? FieldI { get; set; }

    public int? FieldJ { get; set; }
}