// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Battleship.Models;

public partial class battleshipContext : DbContext
{
    public battleshipContext(DbContextOptions<battleshipContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Battleground> Battlegrounds { get; set; }

    public virtual DbSet<Match> Matches { get; set; }

    public virtual DbSet<Ship> Ships { get; set; }

    public virtual DbSet<ShipsBattleground> ShipsBattlegrounds { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Battleground>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("battleground_pkey");

            entity.ToTable("battleground");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.FieldA).HasColumnName("field_a");
            entity.Property(e => e.FieldB).HasColumnName("field_b");
            entity.Property(e => e.FieldC).HasColumnName("field_c");
            entity.Property(e => e.FieldD).HasColumnName("field_d");
            entity.Property(e => e.FieldE).HasColumnName("field_e");
            entity.Property(e => e.FieldF).HasColumnName("field_f");
            entity.Property(e => e.FieldG).HasColumnName("field_g");
            entity.Property(e => e.FieldH).HasColumnName("field_h");
            entity.Property(e => e.FieldHost).HasColumnName("field_host");
            entity.Property(e => e.FieldI).HasColumnName("field_i");
            entity.Property(e => e.FieldJ).HasColumnName("field_j");
            entity.Property(e => e.IdMatch).HasColumnName("id_match");
            entity.Property(e => e.YCord).HasColumnName("y_cord");
        });

        modelBuilder.Entity<Match>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("match_pkey");

            entity.ToTable("match");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Done).HasColumnName("done");
            entity.Property(e => e.IdHost).HasColumnName("id_host");
            entity.Property(e => e.IdParticipant).HasColumnName("id_participant");
            entity.Property(e => e.MatchName)
                .HasMaxLength(255)
                .HasColumnName("match_name");
            entity.Property(e => e.TurnHost).HasColumnName("turn_host");
        });

        modelBuilder.Entity<Ship>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("ship_pkey");

            entity.ToTable("ship");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Boxes).HasColumnName("boxes");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
        });

        modelBuilder.Entity<ShipsBattleground>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("ships_battleground_pkey");

            entity.ToTable("ships_battleground");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Across).HasColumnName("across");
            entity.Property(e => e.IdMatch).HasColumnName("id_match");
            entity.Property(e => e.IdShip).HasColumnName("id_ship");
            entity.Property(e => e.ShipHost).HasColumnName("ship_host");
            entity.Property(e => e.XCord).HasColumnName("x_cord");
            entity.Property(e => e.YCord).HasColumnName("y_cord");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("users_pkey");

            entity.ToTable("users");

            entity.HasIndex(e => e.Username, "users_username_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.PwHash)
                .HasMaxLength(255)
                .HasColumnName("pw_hash");
            entity.Property(e => e.Username)
                .HasMaxLength(255)
                .HasColumnName("username");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}