// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Battleship.Models;

public partial class Match
{
    public int Id { get; set; }

    public string MatchName { get; set; }

    public int? IdHost { get; set; }

    public int? IdParticipant { get; set; }

    public bool? Done { get; set; }

    public bool? TurnHost { get; set; }
}