// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Battleship.Models;

public partial class Ship
{
    public int Id { get; set; }

    public int? Boxes { get; set; }

    public int? Quantity { get; set; }

    public string Name { get; set; }
}