// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Battleship.Models;

public partial class ShipsBattleground
{
    public int Id { get; set; }

    public int? IdMatch { get; set; }

    public int? IdShip { get; set; }

    public bool? ShipHost { get; set; }

    public int? XCord { get; set; }

    public int? YCord { get; set; }

    public bool? Across { get; set; }
}